// Static data constants for the voter map client.
// No logic lives here. Every export is a frozen-in-spirit lookup table.

export const PARTY_COLOR = { R: "#c0392b", D: "#2471a3" };

export const PARTY_LABEL = {
  R: "Republican",
  D: "Democrat",
  Independent: "Independent",
};

export const FIPS_TO_ABBR = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT",
  "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL",
  "18": "IN", "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD",
  "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO", "30": "MT", "31": "NE",
  "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
  "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV",
  "55": "WI", "56": "WY"
};

// Precomputed reverse lookup (avoids O(n) .find() scans in the hot path).
export const ABBR_TO_FIPS = Object.fromEntries(
  Object.entries(FIPS_TO_ABBR).map(([fips, abbr]) => [abbr, fips])
);

export const STATE_CENTROIDS = {
  "AL": [32.806, -86.791], "AK": [64.2, -153.0], "AZ": [34.048, -111.093],
  "AR": [34.969, -92.373], "CA": [36.778, -119.418], "CO": [39.113, -105.358],
  "CT": [41.598, -72.755], "DE": [39.318, -75.507], "FL": [27.994, -81.760],
  "GA": [32.678, -83.223], "HI": [20.798, -156.331], "ID": [44.068, -114.742],
  "IL": [40.349, -88.986], "IN": [39.849, -86.258], "IA": [42.011, -93.210],
  "KS": [38.526, -96.726], "KY": [37.668, -84.670], "LA": [31.169, -91.867],
  "ME": [44.693, -69.381], "MD": [39.063, -76.802], "MA": [42.230, -71.530],
  "MI": [44.314, -85.602], "MN": [46.392, -94.636], "MS": [32.741, -89.678],
  "MO": [38.456, -92.288], "MT": [46.921, -110.454], "NE": [41.492, -99.901],
  "NV": [38.802, -116.419], "NH": [43.193, -71.572], "NJ": [40.058, -74.405],
  "NM": [34.307, -106.018], "NY": [42.165, -74.948], "NC": [35.782, -80.793],
  "ND": [47.528, -99.784], "OH": [40.388, -82.764], "OK": [35.565, -96.928],
  "OR": [43.804, -120.554], "PA": [41.203, -77.194], "RI": [41.742, -71.477],
  "SC": [33.836, -81.163], "SD": [44.299, -99.438], "TN": [35.517, -86.580],
  "TX": [31.054, -97.563], "UT": [39.320, -111.093], "VT": [44.558, -72.577],
  "VA": [37.431, -78.656], "WA": [47.400, -121.490], "WV": [38.491, -80.954],
  "WI": [43.784, -88.787], "WY": [43.075, -107.290]
};

// State abbrs -> full name, underscore-escaped for URL building (e.g. Ballotpedia).
export const ABBR_TO_BALLOTPEDIA_STATE = {
  "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California",
  "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia",
  "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
  "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
  "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
  "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada",
  "NH": "New_Hampshire", "NJ": "New_Jersey", "NM": "New_Mexico", "NY": "New_York",
  "NC": "North_Carolina", "ND": "North_Dakota", "OH": "Ohio", "OK": "Oklahoma",
  "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode_Island", "SC": "South_Carolina",
  "SD": "South_Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont",
  "VA": "Virginia", "WA": "Washington", "WV": "West_Virginia", "WI": "Wisconsin",
  "WY": "Wyoming"
};

// Per-state legislative-body, chamber, member-title, and Ballotpedia URL
// slug metadata. Mirrors scripts/constants.py::STATE_LEGISLATURE_META.
//
// Display strings are used in the sidebar; *_url_slug values are used to
// build Ballotpedia links of the form
//   https://ballotpedia.org/<body_url_slug>
//   https://ballotpedia.org/<upper_url_slug>_District_<N>
//   https://ballotpedia.org/<lower_url_slug>_District_<N>
//
// Nebraska is unicameral — its lower_* fields are null; the lower-house
// toggle is suppressed for it. DC and territories are absent — the toggle
// hides entirely when no entry exists for the selected state.
export const STATE_LEGISLATURE_META = {
  AL: { body: "Alabama Legislature", body_url_slug: "Alabama_State_Legislature",
        upper_chamber: "Alabama State Senate", upper_member: "Senator", upper_url_slug: "Alabama_State_Senate",
        lower_chamber: "Alabama House of Representatives", lower_member: "Representative", lower_url_slug: "Alabama_House_of_Representatives" },
  AK: { body: "Alaska State Legislature", body_url_slug: "Alaska_State_Legislature",
        upper_chamber: "Alaska State Senate", upper_member: "Senator", upper_url_slug: "Alaska_State_Senate",
        lower_chamber: "Alaska House of Representatives", lower_member: "Representative", lower_url_slug: "Alaska_House_of_Representatives" },
  AZ: { body: "Arizona State Legislature", body_url_slug: "Arizona_State_Legislature",
        upper_chamber: "Arizona State Senate", upper_member: "Senator", upper_url_slug: "Arizona_State_Senate",
        lower_chamber: "Arizona House of Representatives", lower_member: "Representative", lower_url_slug: "Arizona_House_of_Representatives" },
  AR: { body: "Arkansas General Assembly", body_url_slug: "Arkansas_General_Assembly",
        upper_chamber: "Arkansas State Senate", upper_member: "Senator", upper_url_slug: "Arkansas_State_Senate",
        lower_chamber: "Arkansas House of Representatives", lower_member: "Representative", lower_url_slug: "Arkansas_House_of_Representatives" },
  CA: { body: "California State Legislature", body_url_slug: "California_State_Legislature",
        upper_chamber: "California State Senate", upper_member: "Senator", upper_url_slug: "California_State_Senate",
        lower_chamber: "California State Assembly", lower_member: "Assemblymember", lower_url_slug: "California_State_Assembly" },
  CO: { body: "Colorado General Assembly", body_url_slug: "Colorado_General_Assembly",
        upper_chamber: "Colorado State Senate", upper_member: "Senator", upper_url_slug: "Colorado_State_Senate",
        lower_chamber: "Colorado House of Representatives", lower_member: "Representative", lower_url_slug: "Colorado_House_of_Representatives" },
  CT: { body: "Connecticut General Assembly", body_url_slug: "Connecticut_General_Assembly",
        upper_chamber: "Connecticut State Senate", upper_member: "Senator", upper_url_slug: "Connecticut_State_Senate",
        lower_chamber: "Connecticut House of Representatives", lower_member: "Representative", lower_url_slug: "Connecticut_House_of_Representatives" },
  DE: { body: "Delaware General Assembly", body_url_slug: "Delaware_General_Assembly",
        upper_chamber: "Delaware State Senate", upper_member: "Senator", upper_url_slug: "Delaware_State_Senate",
        lower_chamber: "Delaware House of Representatives", lower_member: "Representative", lower_url_slug: "Delaware_House_of_Representatives" },
  FL: { body: "Florida Legislature", body_url_slug: "Florida_State_Legislature",
        upper_chamber: "Florida State Senate", upper_member: "Senator", upper_url_slug: "Florida_State_Senate",
        lower_chamber: "Florida House of Representatives", lower_member: "Representative", lower_url_slug: "Florida_House_of_Representatives" },
  GA: { body: "Georgia General Assembly", body_url_slug: "Georgia_General_Assembly",
        upper_chamber: "Georgia State Senate", upper_member: "Senator", upper_url_slug: "Georgia_State_Senate",
        lower_chamber: "Georgia House of Representatives", lower_member: "Representative", lower_url_slug: "Georgia_House_of_Representatives" },
  HI: { body: "Hawaii State Legislature", body_url_slug: "Hawaii_State_Legislature",
        upper_chamber: "Hawaii State Senate", upper_member: "Senator", upper_url_slug: "Hawaii_State_Senate",
        lower_chamber: "Hawaii House of Representatives", lower_member: "Representative", lower_url_slug: "Hawaii_House_of_Representatives" },
  ID: { body: "Idaho Legislature", body_url_slug: "Idaho_State_Legislature",
        upper_chamber: "Idaho State Senate", upper_member: "Senator", upper_url_slug: "Idaho_State_Senate",
        lower_chamber: "Idaho House of Representatives", lower_member: "Representative", lower_url_slug: "Idaho_House_of_Representatives" },
  IL: { body: "Illinois General Assembly", body_url_slug: "Illinois_General_Assembly",
        upper_chamber: "Illinois State Senate", upper_member: "Senator", upper_url_slug: "Illinois_State_Senate",
        lower_chamber: "Illinois House of Representatives", lower_member: "Representative", lower_url_slug: "Illinois_House_of_Representatives" },
  IN: { body: "Indiana General Assembly", body_url_slug: "Indiana_General_Assembly",
        upper_chamber: "Indiana State Senate", upper_member: "Senator", upper_url_slug: "Indiana_State_Senate",
        lower_chamber: "Indiana House of Representatives", lower_member: "Representative", lower_url_slug: "Indiana_House_of_Representatives" },
  IA: { body: "Iowa General Assembly", body_url_slug: "Iowa_General_Assembly",
        upper_chamber: "Iowa State Senate", upper_member: "Senator", upper_url_slug: "Iowa_State_Senate",
        lower_chamber: "Iowa House of Representatives", lower_member: "Representative", lower_url_slug: "Iowa_House_of_Representatives" },
  KS: { body: "Kansas Legislature", body_url_slug: "Kansas_State_Legislature",
        upper_chamber: "Kansas State Senate", upper_member: "Senator", upper_url_slug: "Kansas_State_Senate",
        lower_chamber: "Kansas House of Representatives", lower_member: "Representative", lower_url_slug: "Kansas_House_of_Representatives" },
  KY: { body: "Kentucky General Assembly", body_url_slug: "Kentucky_General_Assembly",
        upper_chamber: "Kentucky State Senate", upper_member: "Senator", upper_url_slug: "Kentucky_State_Senate",
        lower_chamber: "Kentucky House of Representatives", lower_member: "Representative", lower_url_slug: "Kentucky_House_of_Representatives" },
  LA: { body: "Louisiana State Legislature", body_url_slug: "Louisiana_State_Legislature",
        upper_chamber: "Louisiana State Senate", upper_member: "Senator", upper_url_slug: "Louisiana_State_Senate",
        lower_chamber: "Louisiana House of Representatives", lower_member: "Representative", lower_url_slug: "Louisiana_House_of_Representatives" },
  ME: { body: "Maine Legislature", body_url_slug: "Maine_State_Legislature",
        upper_chamber: "Maine State Senate", upper_member: "Senator", upper_url_slug: "Maine_State_Senate",
        lower_chamber: "Maine House of Representatives", lower_member: "Representative", lower_url_slug: "Maine_House_of_Representatives" },
  MD: { body: "Maryland General Assembly", body_url_slug: "Maryland_General_Assembly",
        upper_chamber: "Maryland State Senate", upper_member: "Senator", upper_url_slug: "Maryland_State_Senate",
        lower_chamber: "Maryland House of Delegates", lower_member: "Delegate", lower_url_slug: "Maryland_House_of_Delegates" },
  MA: { body: "Massachusetts General Court", body_url_slug: "Massachusetts_General_Court",
        upper_chamber: "Massachusetts State Senate", upper_member: "Senator", upper_url_slug: "Massachusetts_State_Senate",
        lower_chamber: "Massachusetts House of Representatives", lower_member: "Representative", lower_url_slug: "Massachusetts_House_of_Representatives" },
  MI: { body: "Michigan Legislature", body_url_slug: "Michigan_State_Legislature",
        upper_chamber: "Michigan State Senate", upper_member: "Senator", upper_url_slug: "Michigan_State_Senate",
        lower_chamber: "Michigan House of Representatives", lower_member: "Representative", lower_url_slug: "Michigan_House_of_Representatives" },
  MN: { body: "Minnesota Legislature", body_url_slug: "Minnesota_State_Legislature",
        upper_chamber: "Minnesota State Senate", upper_member: "Senator", upper_url_slug: "Minnesota_State_Senate",
        lower_chamber: "Minnesota House of Representatives", lower_member: "Representative", lower_url_slug: "Minnesota_House_of_Representatives" },
  MS: { body: "Mississippi Legislature", body_url_slug: "Mississippi_State_Legislature",
        upper_chamber: "Mississippi State Senate", upper_member: "Senator", upper_url_slug: "Mississippi_State_Senate",
        lower_chamber: "Mississippi House of Representatives", lower_member: "Representative", lower_url_slug: "Mississippi_House_of_Representatives" },
  MO: { body: "Missouri General Assembly", body_url_slug: "Missouri_General_Assembly",
        upper_chamber: "Missouri State Senate", upper_member: "Senator", upper_url_slug: "Missouri_State_Senate",
        lower_chamber: "Missouri House of Representatives", lower_member: "Representative", lower_url_slug: "Missouri_House_of_Representatives" },
  MT: { body: "Montana Legislature", body_url_slug: "Montana_State_Legislature",
        upper_chamber: "Montana State Senate", upper_member: "Senator", upper_url_slug: "Montana_State_Senate",
        lower_chamber: "Montana House of Representatives", lower_member: "Representative", lower_url_slug: "Montana_House_of_Representatives" },
  NE: { body: "Nebraska Legislature", body_url_slug: "Nebraska_State_Legislature",
        upper_chamber: "Nebraska Legislature", upper_member: "Senator", upper_url_slug: "Nebraska_State_Senate",
        lower_chamber: null, lower_member: null, lower_url_slug: null },
  NV: { body: "Nevada Legislature", body_url_slug: "Nevada_State_Legislature",
        upper_chamber: "Nevada State Senate", upper_member: "Senator", upper_url_slug: "Nevada_State_Senate",
        lower_chamber: "Nevada State Assembly", lower_member: "Assemblymember", lower_url_slug: "Nevada_State_Assembly" },
  NH: { body: "New Hampshire General Court", body_url_slug: "New_Hampshire_General_Court",
        upper_chamber: "New Hampshire State Senate", upper_member: "Senator", upper_url_slug: "New_Hampshire_State_Senate",
        lower_chamber: "New Hampshire House of Representatives", lower_member: "Representative", lower_url_slug: "New_Hampshire_House_of_Representatives" },
  NJ: { body: "New Jersey Legislature", body_url_slug: "New_Jersey_State_Legislature",
        upper_chamber: "New Jersey State Senate", upper_member: "Senator", upper_url_slug: "New_Jersey_State_Senate",
        lower_chamber: "New Jersey General Assembly", lower_member: "Assemblymember", lower_url_slug: "New_Jersey_General_Assembly" },
  NM: { body: "New Mexico Legislature", body_url_slug: "New_Mexico_State_Legislature",
        upper_chamber: "New Mexico State Senate", upper_member: "Senator", upper_url_slug: "New_Mexico_State_Senate",
        lower_chamber: "New Mexico House of Representatives", lower_member: "Representative", lower_url_slug: "New_Mexico_House_of_Representatives" },
  NY: { body: "New York State Legislature", body_url_slug: "New_York_State_Legislature",
        upper_chamber: "New York State Senate", upper_member: "Senator", upper_url_slug: "New_York_State_Senate",
        lower_chamber: "New York State Assembly", lower_member: "Assemblymember", lower_url_slug: "New_York_State_Assembly" },
  NC: { body: "North Carolina General Assembly", body_url_slug: "North_Carolina_General_Assembly",
        upper_chamber: "North Carolina State Senate", upper_member: "Senator", upper_url_slug: "North_Carolina_State_Senate",
        lower_chamber: "North Carolina House of Representatives", lower_member: "Representative", lower_url_slug: "North_Carolina_House_of_Representatives" },
  ND: { body: "North Dakota Legislative Assembly", body_url_slug: "North_Dakota_Legislative_Assembly",
        upper_chamber: "North Dakota State Senate", upper_member: "Senator", upper_url_slug: "North_Dakota_State_Senate",
        lower_chamber: "North Dakota House of Representatives", lower_member: "Representative", lower_url_slug: "North_Dakota_House_of_Representatives" },
  OH: { body: "Ohio General Assembly", body_url_slug: "Ohio_General_Assembly",
        upper_chamber: "Ohio State Senate", upper_member: "Senator", upper_url_slug: "Ohio_State_Senate",
        lower_chamber: "Ohio House of Representatives", lower_member: "Representative", lower_url_slug: "Ohio_House_of_Representatives" },
  OK: { body: "Oklahoma Legislature", body_url_slug: "Oklahoma_State_Legislature",
        upper_chamber: "Oklahoma State Senate", upper_member: "Senator", upper_url_slug: "Oklahoma_State_Senate",
        lower_chamber: "Oklahoma House of Representatives", lower_member: "Representative", lower_url_slug: "Oklahoma_House_of_Representatives" },
  OR: { body: "Oregon Legislative Assembly", body_url_slug: "Oregon_Legislative_Assembly",
        upper_chamber: "Oregon State Senate", upper_member: "Senator", upper_url_slug: "Oregon_State_Senate",
        lower_chamber: "Oregon House of Representatives", lower_member: "Representative", lower_url_slug: "Oregon_House_of_Representatives" },
  PA: { body: "Pennsylvania General Assembly", body_url_slug: "Pennsylvania_General_Assembly",
        upper_chamber: "Pennsylvania State Senate", upper_member: "Senator", upper_url_slug: "Pennsylvania_State_Senate",
        lower_chamber: "Pennsylvania House of Representatives", lower_member: "Representative", lower_url_slug: "Pennsylvania_House_of_Representatives" },
  RI: { body: "Rhode Island General Assembly", body_url_slug: "Rhode_Island_General_Assembly",
        upper_chamber: "Rhode Island State Senate", upper_member: "Senator", upper_url_slug: "Rhode_Island_State_Senate",
        lower_chamber: "Rhode Island House of Representatives", lower_member: "Representative", lower_url_slug: "Rhode_Island_House_of_Representatives" },
  SC: { body: "South Carolina General Assembly", body_url_slug: "South_Carolina_General_Assembly",
        upper_chamber: "South Carolina State Senate", upper_member: "Senator", upper_url_slug: "South_Carolina_State_Senate",
        lower_chamber: "South Carolina House of Representatives", lower_member: "Representative", lower_url_slug: "South_Carolina_House_of_Representatives" },
  SD: { body: "South Dakota Legislature", body_url_slug: "South_Dakota_State_Legislature",
        upper_chamber: "South Dakota State Senate", upper_member: "Senator", upper_url_slug: "South_Dakota_State_Senate",
        lower_chamber: "South Dakota House of Representatives", lower_member: "Representative", lower_url_slug: "South_Dakota_House_of_Representatives" },
  TN: { body: "Tennessee General Assembly", body_url_slug: "Tennessee_General_Assembly",
        upper_chamber: "Tennessee State Senate", upper_member: "Senator", upper_url_slug: "Tennessee_State_Senate",
        lower_chamber: "Tennessee House of Representatives", lower_member: "Representative", lower_url_slug: "Tennessee_House_of_Representatives" },
  TX: { body: "Texas Legislature", body_url_slug: "Texas_State_Legislature",
        upper_chamber: "Texas State Senate", upper_member: "Senator", upper_url_slug: "Texas_State_Senate",
        lower_chamber: "Texas House of Representatives", lower_member: "Representative", lower_url_slug: "Texas_House_of_Representatives" },
  UT: { body: "Utah State Legislature", body_url_slug: "Utah_State_Legislature",
        upper_chamber: "Utah State Senate", upper_member: "Senator", upper_url_slug: "Utah_State_Senate",
        lower_chamber: "Utah House of Representatives", lower_member: "Representative", lower_url_slug: "Utah_House_of_Representatives" },
  VT: { body: "Vermont General Assembly", body_url_slug: "Vermont_General_Assembly",
        upper_chamber: "Vermont State Senate", upper_member: "Senator", upper_url_slug: "Vermont_State_Senate",
        lower_chamber: "Vermont House of Representatives", lower_member: "Representative", lower_url_slug: "Vermont_House_of_Representatives" },
  VA: { body: "Virginia General Assembly", body_url_slug: "Virginia_General_Assembly",
        upper_chamber: "Senate of Virginia", upper_member: "Senator", upper_url_slug: "Virginia_State_Senate",
        lower_chamber: "Virginia House of Delegates", lower_member: "Delegate", lower_url_slug: "Virginia_House_of_Delegates" },
  WA: { body: "Washington State Legislature", body_url_slug: "Washington_State_Legislature",
        upper_chamber: "Washington State Senate", upper_member: "Senator", upper_url_slug: "Washington_State_Senate",
        lower_chamber: "Washington House of Representatives", lower_member: "Representative", lower_url_slug: "Washington_House_of_Representatives" },
  WV: { body: "West Virginia Legislature", body_url_slug: "West_Virginia_State_Legislature",
        upper_chamber: "West Virginia State Senate", upper_member: "Senator", upper_url_slug: "West_Virginia_State_Senate",
        lower_chamber: "West Virginia House of Delegates", lower_member: "Delegate", lower_url_slug: "West_Virginia_House_of_Delegates" },
  WI: { body: "Wisconsin State Legislature", body_url_slug: "Wisconsin_State_Legislature",
        upper_chamber: "Wisconsin State Senate", upper_member: "Senator", upper_url_slug: "Wisconsin_State_Senate",
        lower_chamber: "Wisconsin State Assembly", lower_member: "Representative", lower_url_slug: "Wisconsin_State_Assembly" },
  WY: { body: "Wyoming Legislature", body_url_slug: "Wyoming_State_Legislature",
        upper_chamber: "Wyoming State Senate", upper_member: "Senator", upper_url_slug: "Wyoming_State_Senate",
        lower_chamber: "Wyoming House of Representatives", lower_member: "Representative", lower_url_slug: "Wyoming_House_of_Representatives" },
};
