"""
Static data constants for the voter map pipeline.

No logic lives here. Each constant is imported by transforms.py (pure
transformations) or prep_data.py (the orchestrator).
"""

# ── 2024 election results (Trump=R, Harris=D) ─────────────────────────────────

ELECTION_2024 = {
    "AL": "R", "AK": "R", "AZ": "R", "AR": "R", "CA": "D", "CO": "D", "CT": "D", "DE": "D",
    "FL": "R", "GA": "R", "HI": "D", "ID": "R", "IL": "D", "IN": "R", "IA": "R", "KS": "R",
    "KY": "R", "LA": "R", "ME": "D", "MD": "D", "MA": "D", "MI": "R", "MN": "D", "MS": "R",
    "MO": "R", "MT": "R", "NE": "R", "NV": "R", "NH": "D", "NJ": "D", "NM": "D", "NY": "D",
    "NC": "R", "ND": "R", "OH": "R", "OK": "R", "OR": "D", "PA": "R", "RI": "D", "SC": "R",
    "SD": "R", "TN": "R", "TX": "R", "UT": "R", "VT": "D", "VA": "D", "WA": "D", "WV": "R",
    "WI": "R", "WY": "R",
}

# ── voter registration links ──────────────────────────────────────────────────

VOTER_REG = {
    "AL": {"url": "https://www.sos.alabama.gov/alabama-votes/voter/register-to-vote", "name": "Alabama Voter Registration"},
    "AK": {"url": "https://voterregistration.alaska.gov/", "name": "Alaska Voter Registration"},
    "AZ": {"url": "https://servicearizona.com/VoterRegistration/", "name": "Arizona Voter Registration"},
    "AR": {"url": "https://www.sos.arkansas.gov/elections/voter-information/voter-registration", "name": "Arkansas Voter Registration"},
    "CA": {"url": "https://registertovote.ca.gov/", "name": "California Voter Registration"},
    "CO": {"url": "https://www.sos.state.co.us/voter/", "name": "Colorado Voter Registration"},
    "CT": {"url": "https://voterregistration.ct.gov/OLVR/welcome.do", "name": "Connecticut Voter Registration"},
    "DE": {"url": "https://ivote.de.gov/VoterView/registrant/newregistrant", "name": "Delaware Voter Registration"},
    "FL": {"url": "https://registertovoteflorida.gov/", "name": "Florida Voter Registration"},
    "GA": {"url": "https://mvp.sos.ga.gov/s/voter-registration", "name": "Georgia Voter Registration"},
    "HI": {"url": "https://olvr.hawaii.gov/", "name": "Hawaii Voter Registration"},
    "ID": {"url": "https://idahovotes.gov/", "name": "Idaho Voter Registration"},
    "IL": {"url": "https://ova.elections.il.gov/", "name": "Illinois Voter Registration"},
    "IN": {"url": "https://indianavoters.in.gov/", "name": "Indiana Voter Registration"},
    "IA": {"url": "https://sos.iowa.gov/elections/voterinformation/voterregistration.html", "name": "Iowa Voter Registration"},
    "KS": {"url": "https://www.kdor.ks.gov/Apps/VoterReg/Default.aspx", "name": "Kansas Voter Registration"},
    "KY": {"url": "https://vrsws.sos.ky.gov/ovrweb/", "name": "Kentucky Voter Registration"},
    "LA": {"url": "https://voterportal.sos.la.gov/Voter-Registration/Register", "name": "Louisiana Voter Registration"},
    "ME": {"url": "https://www.maine.gov/sos/cec/elec/voter-info/votereg.html", "name": "Maine Voter Registration"},
    "MD": {"url": "https://voterservices.elections.maryland.gov/OnlineVoterRegistration/InstructionsStep1", "name": "Maryland Voter Registration"},
    "MA": {"url": "https://www.sec.state.ma.us/OVR/", "name": "Massachusetts Voter Registration"},
    "MI": {"url": "https://mvic.sos.state.mi.us/RegisterVoter", "name": "Michigan Voter Registration"},
    "MN": {"url": "https://mnvotes.sos.state.mn.us/VoterRegistration/VoterRegistrationMain.aspx", "name": "Minnesota Voter Registration"},
    "MS": {"url": "https://www.sos.ms.gov/voter-registration-information", "name": "Mississippi Voter Registration"},
    "MO": {"url": "https://www.sos.mo.gov/elections/goVoteMissouri/register.aspx", "name": "Missouri Voter Registration"},
    "MT": {"url": "https://sosmt.gov/elections/vote/", "name": "Montana Voter Registration"},
    "NE": {"url": "https://www.nebraska.gov/apps-sos-voter-registration/", "name": "Nebraska Voter Registration"},
    "NV": {"url": "https://www.nvsos.gov/sos/elections/voters", "name": "Nevada Voter Registration"},
    "NH": {"url": "https://www.sos.nh.gov/elections/voters/register-vote", "name": "New Hampshire Voter Registration"},
    "NJ": {"url": "https://voter.svrs.nj.gov/register", "name": "New Jersey Voter Registration"},
    "NM": {"url": "https://www.sos.nm.gov/voting-and-elections/voter-information-portal/voter-registration-information/", "name": "New Mexico Voter Registration"},
    "NY": {"url": "https://www.elections.ny.gov/VoterRegister.html", "name": "New York Voter Registration"},
    "NC": {"url": "https://www.ncsbe.gov/registering", "name": "North Carolina Voter Registration"},
    "ND": {"url": "https://vip.sos.nd.gov/PortalList.aspx", "name": "North Dakota Voter Registration"},
    "OH": {"url": "https://olvr.ohiosos.gov/", "name": "Ohio Voter Registration"},
    "OK": {"url": "https://www.elections.ok.gov/", "name": "Oklahoma Voter Registration"},
    "OR": {"url": "https://sos.oregon.gov/voting/pages/register.aspx", "name": "Oregon Voter Registration"},
    "PA": {"url": "https://www.vote.pa.gov/Register-to-Vote/Pages/default.aspx", "name": "Pennsylvania Voter Registration"},
    "RI": {"url": "https://vote.sos.ri.gov/Voter/RegisterToVote", "name": "Rhode Island Voter Registration"},
    "SC": {"url": "https://www.scvotes.gov/voter-registration", "name": "South Carolina Voter Registration"},
    "SD": {"url": "https://sdsos.gov/elections-voting/voting/register-to-vote.aspx", "name": "South Dakota Voter Registration"},
    "TN": {"url": "https://ovr.govote.tn.gov/", "name": "Tennessee Voter Registration"},
    "TX": {"url": "https://www.votetexas.gov/register-to-vote/", "name": "Texas Voter Registration"},
    "UT": {"url": "https://vote.utah.gov/", "name": "Utah Voter Registration"},
    "VT": {"url": "https://olvr.vermont.gov/", "name": "Vermont Voter Registration"},
    "VA": {"url": "https://www.elections.virginia.gov/registration/", "name": "Virginia Voter Registration"},
    "WA": {"url": "https://www.sos.wa.gov/elections/register.aspx", "name": "Washington Voter Registration"},
    "WV": {"url": "https://ovr.sos.wv.gov/Register/Landing", "name": "West Virginia Voter Registration"},
    "WI": {"url": "https://myvote.wi.gov/en-us/Register-To-Vote", "name": "Wisconsin Voter Registration"},
    "WY": {"url": "https://sos.wyo.gov/Elections/", "name": "Wyoming Voter Registration"},
}

# ── 2025 redistricting metadata ───────────────────────────────────────────────
# Maps FIPS code -> (state abbr, local zip filename, download URL)
# Source: American Redistricting Project (thearp.org)

REDISTRICTED = {
    "06": ("CA", "CA_CD_2025.zip", "https://thearp.org/documents/19013/ca_cd_prop50_EnhHRHd.zip"),
    "29": ("MO", "MO_CD_2025.zip", "https://thearp.org/documents/18733/MO_CD_MO_2025.zip"),
    "37": ("NC", "NC_CD_2025.zip", "https://thearp.org/documents/18957/nc_cd_2025.zip"),
    "39": ("OH", "OH_CD_2025.zip", "https://thearp.org/documents/18960/OH_CD_10302025.zip"),
    "48": ("TX", "TX_CD_2025.zip", "https://thearp.org/documents/18577/tx_cd_Enacted_2025.zip"),
    "49": ("UT", "UT_CD_2025.zip", "https://thearp.org/documents/19051/UT_CD_CourtOrdered11112025.zip"),
}

# ── state name <-> abbr lookup ────────────────────────────────────────────────

STATE_NAME_TO_ABBR = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA",
    "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE", "Florida": "FL", "Georgia": "GA",
    "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD",
    "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS",
    "Missouri": "MO", "Montana": "MT", "Nebraska": "NE", "Nevada": "NV",
    "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY",
    "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK",
    "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC",
    "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT",
    "Virginia": "VA", "Washington": "WA", "West Virginia": "WV", "Wisconsin": "WI",
    "Wyoming": "WY",
}

# Inverted lookup (computed once at module load)
ABBR_TO_STATE_NAME = {abbr: name for name, abbr in STATE_NAME_TO_ABBR.items()}

# ── state legislature naming + URL metadata ──────────────────────────────────
# Per-state names of the legislative body and its chambers, plus Ballotpedia
# URL slugs. Display strings are used in the sidebar; slugs are used to build
# Ballotpedia links of the form:
#   https://ballotpedia.org/<body_url_slug>
#   https://ballotpedia.org/<upper_url_slug>_District_<N>
#   https://ballotpedia.org/<lower_url_slug>_District_<N>
#
# Nebraska is unicameral — only an upper chamber (the "Nebraska Legislature").
# Its `lower_*` fields are None and the lower-house toggle is suppressed.
#
# Sources: each state's official legislative-body site + Ballotpedia URL
# conventions verified spot-wise (VA, CA, NJ, MA, NE, ND).

STATE_LEGISLATURE_META = {
    "AL": {"body": "Alabama Legislature", "body_url_slug": "Alabama_State_Legislature",
           "upper_chamber": "Alabama State Senate", "upper_member": "Senator",
           "upper_url_slug": "Alabama_State_Senate",
           "lower_chamber": "Alabama House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Alabama_House_of_Representatives"},
    "AK": {"body": "Alaska State Legislature", "body_url_slug": "Alaska_State_Legislature",
           "upper_chamber": "Alaska State Senate", "upper_member": "Senator",
           "upper_url_slug": "Alaska_State_Senate",
           "lower_chamber": "Alaska House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Alaska_House_of_Representatives"},
    "AZ": {"body": "Arizona State Legislature", "body_url_slug": "Arizona_State_Legislature",
           "upper_chamber": "Arizona State Senate", "upper_member": "Senator",
           "upper_url_slug": "Arizona_State_Senate",
           "lower_chamber": "Arizona House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Arizona_House_of_Representatives"},
    "AR": {"body": "Arkansas General Assembly", "body_url_slug": "Arkansas_General_Assembly",
           "upper_chamber": "Arkansas State Senate", "upper_member": "Senator",
           "upper_url_slug": "Arkansas_State_Senate",
           "lower_chamber": "Arkansas House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Arkansas_House_of_Representatives"},
    "CA": {"body": "California State Legislature", "body_url_slug": "California_State_Legislature",
           "upper_chamber": "California State Senate", "upper_member": "Senator",
           "upper_url_slug": "California_State_Senate",
           "lower_chamber": "California State Assembly", "lower_member": "Assemblymember",
           "lower_url_slug": "California_State_Assembly"},
    "CO": {"body": "Colorado General Assembly", "body_url_slug": "Colorado_General_Assembly",
           "upper_chamber": "Colorado State Senate", "upper_member": "Senator",
           "upper_url_slug": "Colorado_State_Senate",
           "lower_chamber": "Colorado House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Colorado_House_of_Representatives"},
    "CT": {"body": "Connecticut General Assembly", "body_url_slug": "Connecticut_General_Assembly",
           "upper_chamber": "Connecticut State Senate", "upper_member": "Senator",
           "upper_url_slug": "Connecticut_State_Senate",
           "lower_chamber": "Connecticut House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Connecticut_House_of_Representatives"},
    "DE": {"body": "Delaware General Assembly", "body_url_slug": "Delaware_General_Assembly",
           "upper_chamber": "Delaware State Senate", "upper_member": "Senator",
           "upper_url_slug": "Delaware_State_Senate",
           "lower_chamber": "Delaware House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Delaware_House_of_Representatives"},
    "FL": {"body": "Florida Legislature", "body_url_slug": "Florida_State_Legislature",
           "upper_chamber": "Florida State Senate", "upper_member": "Senator",
           "upper_url_slug": "Florida_State_Senate",
           "lower_chamber": "Florida House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Florida_House_of_Representatives"},
    "GA": {"body": "Georgia General Assembly", "body_url_slug": "Georgia_General_Assembly",
           "upper_chamber": "Georgia State Senate", "upper_member": "Senator",
           "upper_url_slug": "Georgia_State_Senate",
           "lower_chamber": "Georgia House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Georgia_House_of_Representatives"},
    "HI": {"body": "Hawaii State Legislature", "body_url_slug": "Hawaii_State_Legislature",
           "upper_chamber": "Hawaii State Senate", "upper_member": "Senator",
           "upper_url_slug": "Hawaii_State_Senate",
           "lower_chamber": "Hawaii House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Hawaii_House_of_Representatives"},
    "ID": {"body": "Idaho Legislature", "body_url_slug": "Idaho_State_Legislature",
           "upper_chamber": "Idaho State Senate", "upper_member": "Senator",
           "upper_url_slug": "Idaho_State_Senate",
           "lower_chamber": "Idaho House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Idaho_House_of_Representatives"},
    "IL": {"body": "Illinois General Assembly", "body_url_slug": "Illinois_General_Assembly",
           "upper_chamber": "Illinois State Senate", "upper_member": "Senator",
           "upper_url_slug": "Illinois_State_Senate",
           "lower_chamber": "Illinois House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Illinois_House_of_Representatives"},
    "IN": {"body": "Indiana General Assembly", "body_url_slug": "Indiana_General_Assembly",
           "upper_chamber": "Indiana State Senate", "upper_member": "Senator",
           "upper_url_slug": "Indiana_State_Senate",
           "lower_chamber": "Indiana House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Indiana_House_of_Representatives"},
    "IA": {"body": "Iowa General Assembly", "body_url_slug": "Iowa_General_Assembly",
           "upper_chamber": "Iowa State Senate", "upper_member": "Senator",
           "upper_url_slug": "Iowa_State_Senate",
           "lower_chamber": "Iowa House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Iowa_House_of_Representatives"},
    "KS": {"body": "Kansas Legislature", "body_url_slug": "Kansas_State_Legislature",
           "upper_chamber": "Kansas State Senate", "upper_member": "Senator",
           "upper_url_slug": "Kansas_State_Senate",
           "lower_chamber": "Kansas House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Kansas_House_of_Representatives"},
    "KY": {"body": "Kentucky General Assembly", "body_url_slug": "Kentucky_General_Assembly",
           "upper_chamber": "Kentucky State Senate", "upper_member": "Senator",
           "upper_url_slug": "Kentucky_State_Senate",
           "lower_chamber": "Kentucky House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Kentucky_House_of_Representatives"},
    "LA": {"body": "Louisiana State Legislature", "body_url_slug": "Louisiana_State_Legislature",
           "upper_chamber": "Louisiana State Senate", "upper_member": "Senator",
           "upper_url_slug": "Louisiana_State_Senate",
           "lower_chamber": "Louisiana House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Louisiana_House_of_Representatives"},
    "ME": {"body": "Maine Legislature", "body_url_slug": "Maine_State_Legislature",
           "upper_chamber": "Maine State Senate", "upper_member": "Senator",
           "upper_url_slug": "Maine_State_Senate",
           "lower_chamber": "Maine House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Maine_House_of_Representatives"},
    "MD": {"body": "Maryland General Assembly", "body_url_slug": "Maryland_General_Assembly",
           "upper_chamber": "Maryland State Senate", "upper_member": "Senator",
           "upper_url_slug": "Maryland_State_Senate",
           "lower_chamber": "Maryland House of Delegates", "lower_member": "Delegate",
           "lower_url_slug": "Maryland_House_of_Delegates"},
    "MA": {"body": "Massachusetts General Court", "body_url_slug": "Massachusetts_General_Court",
           "upper_chamber": "Massachusetts State Senate", "upper_member": "Senator",
           "upper_url_slug": "Massachusetts_State_Senate",
           "lower_chamber": "Massachusetts House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Massachusetts_House_of_Representatives"},
    "MI": {"body": "Michigan Legislature", "body_url_slug": "Michigan_State_Legislature",
           "upper_chamber": "Michigan State Senate", "upper_member": "Senator",
           "upper_url_slug": "Michigan_State_Senate",
           "lower_chamber": "Michigan House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Michigan_House_of_Representatives"},
    "MN": {"body": "Minnesota Legislature", "body_url_slug": "Minnesota_State_Legislature",
           "upper_chamber": "Minnesota State Senate", "upper_member": "Senator",
           "upper_url_slug": "Minnesota_State_Senate",
           "lower_chamber": "Minnesota House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Minnesota_House_of_Representatives"},
    "MS": {"body": "Mississippi Legislature", "body_url_slug": "Mississippi_State_Legislature",
           "upper_chamber": "Mississippi State Senate", "upper_member": "Senator",
           "upper_url_slug": "Mississippi_State_Senate",
           "lower_chamber": "Mississippi House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Mississippi_House_of_Representatives"},
    "MO": {"body": "Missouri General Assembly", "body_url_slug": "Missouri_General_Assembly",
           "upper_chamber": "Missouri State Senate", "upper_member": "Senator",
           "upper_url_slug": "Missouri_State_Senate",
           "lower_chamber": "Missouri House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Missouri_House_of_Representatives"},
    "MT": {"body": "Montana Legislature", "body_url_slug": "Montana_State_Legislature",
           "upper_chamber": "Montana State Senate", "upper_member": "Senator",
           "upper_url_slug": "Montana_State_Senate",
           "lower_chamber": "Montana House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Montana_House_of_Representatives"},
    "NE": {"body": "Nebraska Legislature", "body_url_slug": "Nebraska_State_Legislature",
           "upper_chamber": "Nebraska Legislature", "upper_member": "Senator",
           "upper_url_slug": "Nebraska_State_Senate",
           "lower_chamber": None, "lower_member": None, "lower_url_slug": None},
    "NV": {"body": "Nevada Legislature", "body_url_slug": "Nevada_State_Legislature",
           "upper_chamber": "Nevada State Senate", "upper_member": "Senator",
           "upper_url_slug": "Nevada_State_Senate",
           "lower_chamber": "Nevada State Assembly", "lower_member": "Assemblymember",
           "lower_url_slug": "Nevada_State_Assembly"},
    "NH": {"body": "New Hampshire General Court", "body_url_slug": "New_Hampshire_General_Court",
           "upper_chamber": "New Hampshire State Senate", "upper_member": "Senator",
           "upper_url_slug": "New_Hampshire_State_Senate",
           "lower_chamber": "New Hampshire House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "New_Hampshire_House_of_Representatives"},
    "NJ": {"body": "New Jersey Legislature", "body_url_slug": "New_Jersey_State_Legislature",
           "upper_chamber": "New Jersey State Senate", "upper_member": "Senator",
           "upper_url_slug": "New_Jersey_State_Senate",
           "lower_chamber": "New Jersey General Assembly", "lower_member": "Assemblymember",
           "lower_url_slug": "New_Jersey_General_Assembly"},
    "NM": {"body": "New Mexico Legislature", "body_url_slug": "New_Mexico_State_Legislature",
           "upper_chamber": "New Mexico State Senate", "upper_member": "Senator",
           "upper_url_slug": "New_Mexico_State_Senate",
           "lower_chamber": "New Mexico House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "New_Mexico_House_of_Representatives"},
    "NY": {"body": "New York State Legislature", "body_url_slug": "New_York_State_Legislature",
           "upper_chamber": "New York State Senate", "upper_member": "Senator",
           "upper_url_slug": "New_York_State_Senate",
           "lower_chamber": "New York State Assembly", "lower_member": "Assemblymember",
           "lower_url_slug": "New_York_State_Assembly"},
    "NC": {"body": "North Carolina General Assembly", "body_url_slug": "North_Carolina_General_Assembly",
           "upper_chamber": "North Carolina State Senate", "upper_member": "Senator",
           "upper_url_slug": "North_Carolina_State_Senate",
           "lower_chamber": "North Carolina House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "North_Carolina_House_of_Representatives"},
    "ND": {"body": "North Dakota Legislative Assembly", "body_url_slug": "North_Dakota_Legislative_Assembly",
           "upper_chamber": "North Dakota State Senate", "upper_member": "Senator",
           "upper_url_slug": "North_Dakota_State_Senate",
           "lower_chamber": "North Dakota House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "North_Dakota_House_of_Representatives"},
    "OH": {"body": "Ohio General Assembly", "body_url_slug": "Ohio_General_Assembly",
           "upper_chamber": "Ohio State Senate", "upper_member": "Senator",
           "upper_url_slug": "Ohio_State_Senate",
           "lower_chamber": "Ohio House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Ohio_House_of_Representatives"},
    "OK": {"body": "Oklahoma Legislature", "body_url_slug": "Oklahoma_State_Legislature",
           "upper_chamber": "Oklahoma State Senate", "upper_member": "Senator",
           "upper_url_slug": "Oklahoma_State_Senate",
           "lower_chamber": "Oklahoma House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Oklahoma_House_of_Representatives"},
    "OR": {"body": "Oregon Legislative Assembly", "body_url_slug": "Oregon_Legislative_Assembly",
           "upper_chamber": "Oregon State Senate", "upper_member": "Senator",
           "upper_url_slug": "Oregon_State_Senate",
           "lower_chamber": "Oregon House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Oregon_House_of_Representatives"},
    "PA": {"body": "Pennsylvania General Assembly", "body_url_slug": "Pennsylvania_General_Assembly",
           "upper_chamber": "Pennsylvania State Senate", "upper_member": "Senator",
           "upper_url_slug": "Pennsylvania_State_Senate",
           "lower_chamber": "Pennsylvania House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Pennsylvania_House_of_Representatives"},
    "RI": {"body": "Rhode Island General Assembly", "body_url_slug": "Rhode_Island_General_Assembly",
           "upper_chamber": "Rhode Island State Senate", "upper_member": "Senator",
           "upper_url_slug": "Rhode_Island_State_Senate",
           "lower_chamber": "Rhode Island House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Rhode_Island_House_of_Representatives"},
    "SC": {"body": "South Carolina General Assembly", "body_url_slug": "South_Carolina_General_Assembly",
           "upper_chamber": "South Carolina State Senate", "upper_member": "Senator",
           "upper_url_slug": "South_Carolina_State_Senate",
           "lower_chamber": "South Carolina House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "South_Carolina_House_of_Representatives"},
    "SD": {"body": "South Dakota Legislature", "body_url_slug": "South_Dakota_State_Legislature",
           "upper_chamber": "South Dakota State Senate", "upper_member": "Senator",
           "upper_url_slug": "South_Dakota_State_Senate",
           "lower_chamber": "South Dakota House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "South_Dakota_House_of_Representatives"},
    "TN": {"body": "Tennessee General Assembly", "body_url_slug": "Tennessee_General_Assembly",
           "upper_chamber": "Tennessee State Senate", "upper_member": "Senator",
           "upper_url_slug": "Tennessee_State_Senate",
           "lower_chamber": "Tennessee House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Tennessee_House_of_Representatives"},
    "TX": {"body": "Texas Legislature", "body_url_slug": "Texas_State_Legislature",
           "upper_chamber": "Texas State Senate", "upper_member": "Senator",
           "upper_url_slug": "Texas_State_Senate",
           "lower_chamber": "Texas House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Texas_House_of_Representatives"},
    "UT": {"body": "Utah State Legislature", "body_url_slug": "Utah_State_Legislature",
           "upper_chamber": "Utah State Senate", "upper_member": "Senator",
           "upper_url_slug": "Utah_State_Senate",
           "lower_chamber": "Utah House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Utah_House_of_Representatives"},
    "VT": {"body": "Vermont General Assembly", "body_url_slug": "Vermont_General_Assembly",
           "upper_chamber": "Vermont State Senate", "upper_member": "Senator",
           "upper_url_slug": "Vermont_State_Senate",
           "lower_chamber": "Vermont House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Vermont_House_of_Representatives"},
    "VA": {"body": "Virginia General Assembly", "body_url_slug": "Virginia_General_Assembly",
           "upper_chamber": "Senate of Virginia", "upper_member": "Senator",
           "upper_url_slug": "Virginia_State_Senate",
           "lower_chamber": "Virginia House of Delegates", "lower_member": "Delegate",
           "lower_url_slug": "Virginia_House_of_Delegates"},
    "WA": {"body": "Washington State Legislature", "body_url_slug": "Washington_State_Legislature",
           "upper_chamber": "Washington State Senate", "upper_member": "Senator",
           "upper_url_slug": "Washington_State_Senate",
           "lower_chamber": "Washington House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Washington_House_of_Representatives"},
    "WV": {"body": "West Virginia Legislature", "body_url_slug": "West_Virginia_State_Legislature",
           "upper_chamber": "West Virginia State Senate", "upper_member": "Senator",
           "upper_url_slug": "West_Virginia_State_Senate",
           "lower_chamber": "West Virginia House of Delegates", "lower_member": "Delegate",
           "lower_url_slug": "West_Virginia_House_of_Delegates"},
    "WI": {"body": "Wisconsin State Legislature", "body_url_slug": "Wisconsin_State_Legislature",
           "upper_chamber": "Wisconsin State Senate", "upper_member": "Senator",
           "upper_url_slug": "Wisconsin_State_Senate",
           "lower_chamber": "Wisconsin State Assembly", "lower_member": "Representative",
           "lower_url_slug": "Wisconsin_State_Assembly"},
    "WY": {"body": "Wyoming Legislature", "body_url_slug": "Wyoming_State_Legislature",
           "upper_chamber": "Wyoming State Senate", "upper_member": "Senator",
           "upper_url_slug": "Wyoming_State_Senate",
           "lower_chamber": "Wyoming House of Representatives", "lower_member": "Representative",
           "lower_url_slug": "Wyoming_House_of_Representatives"},
}

# ── manual legislator overrides (for seats missing from upstream data) ───────
# Applied only when upstream `congress-legislators` has not yet filled the seat.

MANUAL_REPS = {
    # Clay Fuller won GA-14 special election April 7, 2026; upstream YAML lags
    ("GA", "14"): {
        "name": "Clay Fuller", "party": "Republican",
        "url": "https://fuller.house.gov",
    },
    # Doug LaMalfa (R) died January 6, 2026
    ("CA", "1"): {
        "name": "Vacant", "party": "", "url": "",
        "vacant": True,
        "vacancy_reason": "Rep. Doug LaMalfa (R) died January 6, 2026. Special election August 4, 2026.",
    },
    # Mikie Sherrill (D) resigned November 20, 2025 (won NJ governor's race)
    ("NJ", "11"): {
        "name": "Vacant", "party": "", "url": "",
        "vacant": True,
        "vacancy_reason": "Rep. Mikie Sherrill (D) resigned November 20, 2025. Special election April 16, 2026.",
    },
}
